name: CI 
on: push 
jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get Branch
      shell: bash #run: echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: branch

    - name: Check Branch
      run: echo "${{ env.branch }}"

    - name: Get Hash
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH
      env:
        id: hash

    - name: Check Hash
      run: echo "${{ env.hash }}"
